### ISSUE TITLE
Vertical scaling for DB container

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Infrastructure#52]
## Description
As a CT user I want a performant db server

## Acceptance criteria

- [ ] Options for the vertical scaling of the db server, and advice for deploying teams (e.g. momentum)

**Comment by GhostOnTheFiber** [comment]
It is possible to vertically scale the nodes where kubes is running the pods. This will then allow for the db container to utilize more resources. It is not possible to just scale say the db container as it already will vertically scale to its needs until it reaches the node constraint. We can horizontally scale the db service to run on multiple nodes. 

I do have to point out that we are not pushing any container very heavily at the moment. For a more advanced deployment I would suggest auto scaling groups in both kubes and azure. So that containers and nodes scale to meet demand. 

I can create a write up on how to set auto-scaling up.
